### ISSUE TITLE
iconBox no packges?

### ISSUE THREAD

**Issue by jiahao-c** [arco-design/arco-plugins#10]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-webpack-plugin/issues)

## 预期解决问题
@arco-plugins/webpack-react 和 @arco-plugins/vite-react 的文档都提到了 `iconBox` 这个属性，并使用 `@arco-design/iconbox-react-dcd-icon` 作为例子。但是 @arco-design 在 npm 上并没有任何 iconbox的包。在 [iconBox 官网](https://arco.design/iconbox/libs) 也没看到有关的包，只有 raw svg。请问这些包是还没发出来吗？

**Comment by jinghm318** [comment]
> * [x]  I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-webpack-plugin/issues)
> 
> ## 预期解决问题
> @arco-plugins/webpack-react 和 @arco-plugins/vite-react 的文档都提到了 `iconBox` 这个属性，并使用 `@arco-design/iconbox-react-dcd-icon` 作为例子。但是 @arco-design 在 npm 上并没有任何 iconbox的包。在 [iconBox 官网](https://arco.design/iconbox/libs) 也没看到有关的包，只有 raw svg。请问这些包是还没发出来吗？

是的，@arco-design/iconbox-react-dcd-icon 内部包，是懂车帝团队使用的，新版本会将这个例子删除；

预计本双月内会有包发出来的，敬请期待
