### ISSUE TITLE
Did not bundle less in dependencies, causing error

### ISSUE THREAD

**Issue by jiahao-c** [arco-design/arco-plugins#11]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-webpack-plugin/issues)

## Basic Info 
- **Package Name And Version:** 
```json
  "dependencies": {
    "@arco-design/web-react": "^2.27.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@arco-plugins/vite-react": "^1.0.2",
    "@arco-themes/react-choral-music": "^0.0.2",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "@vitejs/plugin-react": "^1.0.7",
    "typescript": "^4.5.4",
    "vite": "^2.7.2"
  }
```
- **Reproduction Link:** https://stackblitz.com/edit/vitejs-vite-yoj5b6?file=src%2FApp.tsx&terminal=dev

## What is expected?
No error. 

## What happened
![image](https://user-images.githubusercontent.com/8275280/147896959-3af954d1-86ab-4744-bb41-704c7ffcf6fe.png)

## Steps to reproduce
**Use the reproduction link**, or
1. Init a new project with Vite
2. add `@arco-design/web-react` and
3. use a theme and a component from arco
4. start project

**Comment by jiahao-c** [comment]
虽然可以通过手动 `install -D less` 来解决，不过如果能省去这一步就更好了～

**Comment by jinghm318** [comment]
> ```json
> devDependencies
> ```
感谢反馈。

不过这个还是建议项目自行安装，不是所有场景都需要使用 less 而且可能涉及到 less 版本等问题，插件只提供按需加载能力。

**Comment by jinghm318** [comment]
> 虽然可以通过手动 `install -D less` 来解决，不过如果能省去这一步就更好了～

感谢反馈。

不过这个还是建议项目自行安装，不是所有场景都需要使用 less 而且可能涉及到 less 版本等问题，插件只提供按需加载能力。

**Comment by jinghm318** [comment]
> 虽然可以通过手动 `install -D less` 来解决，不过如果能省去这一步就更好了～
@jiahao-c 

感谢反馈。
不过这个还是建议项目自行安装，不是所有场景都需要使用 less 而且可能涉及到 less 版本等问题，插件只提供按需加载能力。
