### ISSUE TITLE
The latest version is 1.4.1, but doc said need at least version 1.5.0

### ISSUE THREAD

**Issue by liuxinqiong** [arco-design/arco-plugins#25]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-webpack-plugin/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/webpack-plugin@1.7.0
- **Framework version:** React
- **Browser:** chrome92.0.4515.159

## What is expected?
works fine when I use the on-demand loading of styles

## Steps to reproduce
It can't work at all when i use 1.4.1.

**Comment by yinkaihui** [comment]
抱歉，文档有误，我们调整下文档。 直接使用 @arco-plugins/webpack-react 即可
