### ISSUE TITLE
希望可以支持vite脚手架

### ISSUE THREAD

**Issue by singod** [arco-design/arco-plugins#3]
希望可以支持vite脚手架的使用，目前使用vite脚手架做开发也不少

**Comment by kirazxyun** [comment]
收到，安排～

**Comment by xiangqunXiao** [comment]
> 收到，安排～

期待 ing

**Comment by jinghm318** [comment]
> 希望可以支持vite脚手架的使用，目前使用vite脚手架做开发也不少

已经做好了，很快就可以发出来了，我们已经用上了  @xiangqunXiao

**Comment by kirazxyun** [comment]
@singod vite 插件出来喽，可以试试 [vite plugin](https://www.npmjs.com/package/@arco-plugins/vite-react)

**Comment by xiangqunXiao** [comment]
Vue 在你们内部是不是用的不多？总是要等 react 支持后再支持
