### ISSUE TITLE
完善 plugin-vite-vue 按需加载功能

### ISSUE THREAD

**Issue by tazyong** [arco-design/arco-plugins#32]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-webpack-plugin/issues)

@jinghm318 @flsion 请审阅以下问题，如果同意修改，这边可以提交两个仓库的 PR 支持

## 现有问题
1. 无法独立支持模板方式的按需加载
	仅支持样式的按需加载，组件代码加载需要依赖 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)
	![image](https://user-images.githubusercontent.com/24738011/192964158-f4e5458b-77bc-42e3-8efd-3767817999c2.png)

2. 部分组件不支持按需加载
	不以组件目录名为前缀命名的组件，按需加载失效，如：`<a-range-picker />`、`<a-doption>`
	PS：虽然子组件其实只需要父组件成功加载样式就能正常显示，但是这样不是很严谨。

3. 非组件也会加载样式导致构建出错
	![image](https://user-images.githubusercontent.com/24738011/192965923-7504b6c6-5aa4-4869-a197-96a2cf8c7f2a.png)
	![image](https://user-images.githubusercontent.com/24738011/192965978-1c8f5aec-f0a5-4d91-8dec-d726b6893320.png)

相关仓库：https://github.com/tazyong/test-vite3

## 预期解决问题
独立支持 import 和 template 两种方式按需加载

## 解决方案
1. 修改组件库 [components.ts](https://github.com/arco-design/arco-design-vue/blob/main/packages/web-vue/components/components.ts) 文件，引用路径具体到组件目录
	![image](https://user-images.githubusercontent.com/24738011/193003052-ac51d01d-c186-4e70-97ea-76ffdddfe500.png)

2. 修改构建插件库匹配组件逻辑，由以上文件获取组件路径

3. 模板方式时构建同时导入组件代码
	![image](https://user-images.githubusercontent.com/24738011/193004281-c095f7e3-002e-4b11-9221-cf4d09a4c359.png)

**Comment by jinghm318** [comment]
@tazyong 非常感谢反馈，目前看起来第二个和第三个是需要尽快解决的，如果你那边已经改好，可以优先提下

**Comment by tazyong** [comment]
@flsion 组件库那边支持修改 `components.ts` 声明文件吗？

**Comment by jinghm318** [comment]
> @tazyong 非常感谢反馈，目前看起来第二个和第三个是需要尽快解决的，如果你那边已经改好，可以优先提下

@tazyong 第三个非组件引入问题是新版本才有的问题，为了防止 react 版本后面也出现这样的情况，我就一起修复了 https://github.com/arco-design/arco-plugins/pull/33

**Comment by tazyong** [comment]
> > @tazyong 非常感谢反馈，目前看起来第二个和第三个是需要尽快解决的，如果你那边已经改好，可以优先提下
> 
> @tazyong 第三个非组件引入问题是新版本才有的问题，为了防止 react 版本后面也出现这样的情况，我就一起修复了 #33

嗯嗯，`isModExist()` 确实解决了这个问题，但还不是最好的方案

**Comment by tazyong** [comment]
@jinghm318 重构了组件查找的逻辑，以上所有功能匀已支持

**Comment by flsion** [comment]
> @flsion 组件库那边支持修改 `components.ts` 声明文件吗？

 `components.ts`  声明文件可以进行修改，这个仅是用来做 ts 提示的

**Comment by tazyong** [comment]
> > @flsion 组件库那边支持修改 `components.ts` 声明文件吗？
> 
>  `components.ts`  声明文件可以进行修改，这个仅是用来做 ts 提示的

现在已经不需要修改了，目前已从 components.ts 和 index.ts 两个文件获取到对应路径了

**Comment by Jioho** [comment]
是否可以提供更细致的开关控制，如 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 插件提供了 exclude 参数可以排除部分组件的按需加载
