### ISSUE TITLE
希望支持Vite 4.0版本使用

### ISSUE THREAD

**Issue by badManPro** [arco-design/arco-plugins#40]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
暂无

## What problem does this feature solve?
vite4.0.0 在vite.config.ts中配置@arco-plugins/vite-react配置时，显示TypeError: vitePluginForArco is not a function，希望可以支持vite4.0.0

**Comment by jinghm318** [comment]
好，这边尽快跟进看下

**Comment by jinghm318** [comment]
@badManPro @k7cd 有 demo 可以复现吗

**Comment by iamcyw** [comment]
vite 使用 react+swc模板创建项目就会遇到这个问题

**Comment by chenguzhen87** [comment]
同问，这个什么时候能解决呢

**Comment by jinghm318** [comment]
> vite 使用 react+swc模板创建项目就会遇到这个问题

收到，这边尽快跟进看下 @iamcyw @chenguzhen87

**Comment by jinghm318** [comment]
@iamcyw @badManPro @chenguzhen87 @k7cd 
我看了下用 react-swc 创建的项目，在引用插件的时候得按照如下的方式：
import { vitePluginForArco } from '@arco-plugins/vite-react';
