### ISSUE TITLE
希望出一个隔壁 infra 组 rspack 的按需加载插件

### ISSUE THREAD

**Issue by xalanq** [arco-design/arco-plugins#44]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-webpack-plugin/issues)

## What are the similar cases of this feature
none

## What problem does this feature solve?
modernjs 都推 v2 了，都加了 rspack 了，内部不支持一波吗 :)

**Comment by SnowingFox** [comment]
可以参考我的unplugin-react-components项目，按需引入

**Comment by jinghm318** [comment]
看已经有了
https://github.com/arco-design/arco-plugins/tree/main/packages/unplugin-react

**Comment by jinghm318** [comment]
看已经有了
https://github.com/arco-design/arco-plugins/tree/main/packages/unplugin-react

**Comment by shenyanshu** [comment]
在modernjs.dev中确实不生效
