### ISSUE TITLE
使用按需打包，自带的图标不显示

### ISSUE THREAD

**Issue by Uranuscsz** [arco-design/arco-plugins#45]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-webpack-plugin/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/webpack-plugin@1.7.0
- **Framework version:** Vue
- **Browser:** chrome111.0.0.0
- **Reproduction Link:** https://github.com/Uranuscsz/arco_demo.git

**Comment by Uranuscsz** [comment]
![f619e749-c292-43f3-9c42-be8153e3fd53](https://user-images.githubusercontent.com/64002265/224199299-4d3f6e6f-e93b-4a8f-9323-8bf73a6804c4.jpeg)

**Comment by Loongphy** [comment]
+1

**Comment by Loongphy** [comment]
根据[REAME.md](https://github.com/arco-design/arco-plugins/blob/main/packages/plugin-vite-vue/README.md) 修改 [Arco-Design-Pro-Vue](https://github.com/arco-design/arco-design-pro-vue)，侧边栏菜单缺少图标
![image](https://user-images.githubusercontent.com/42089082/224644230-9375df19-7799-4abc-b324-60df6764a8f9.png)

**Comment by jinghm318** [comment]
@Uranuscsz @Loongphy 已修正，升级到1.4.4看看
